name: dev CI

# Run this workflow on commits, tags, PRs on all branches
on:
  push:
  pull_request:
    branches: ["**"]

jobs:
  build:
  # Run tests on ubuntu linux
    runs-on: ubuntu-latest

    # Run Mocha parser test suite
    steps:
      - uses: actions/checkout@v2
      - name: Mocha Parser Tests
        run: |
          cd extension
          npm install
          npm run test-mocha
